# Site settings
title: WF Blog
SEOTitle: 文峰的博客 | WF Blog
header-img: img/post-bg-desk.jpg
email: huangwenfeng1993@sina.com
description: "Simple,So charming..."
keyword: "Java,Linux"
url: "http://wenfengSAT.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/wenfengSAT/wenfengSAT.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Simple,So charming..."
sidebar-avatar: /img/about-BY-gentle.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     大明朝的铜币
#zhihu_username:     wenfengSAT
github_username:    wenfengSAT
#facebook_username:  wenfengSAT
jianshu_username:   wenfengSAT
#twitter_username:   wenfengSAT




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]


# plugins
plugins:
    - jekyll-paginate


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: wenfengSAT

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 8a5d3d390c3d5a508b8b   #生成的clientID
  clientSecret: 4672c8bb4123eda57407bd935e7062ff0b861797  #同上
  repo: wenfengSAT.github.io    #仓库名称
  owner: wenfengSAT    #github用户名
  admin: wenfengSAT
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: ''            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 2              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
   {
        title: "简书",
        href: "http://www.jianshu.com/"
    },
	{
        title: "3304",
        href: "http://106.14.191.238:8080/3304/"
    },
	{
        title: "wenfengSAT",
        href: "http://106.14.191.238:8080/YYT/"
    }
]
